### ISSUE TITLE
module can not compile for nodejs 12.0.0

### ISSUE THREAD

**Issue by crostine** [saghul/node-abstractsocket#17]
Hello,

Today I updated my nodejs to version 12.0.0 and updated the node_modules for my repositories.
I can't seem to install this module. I recorded the output and placed it in this [Gist](https://gist.github.com/crostine/208b9da6c7e3f190c0e0538a08edb4b3)
it appears that the V8 api changed somewhat and is causing these problems.

**Comment by acrisci** [comment]
Yeah this is a problem for me as well with [node-dbus-next](https://github.com/acrisci/node-dbus-next).

**Comment by saghul** [comment]
Oops, sorry folks, missed this one. I won't have time to look into this for a few weeks. Any PR is welcome.

**Comment by acrisci** [comment]
#18
