### ISSUE TITLE
Can't build on OS X

### ISSUE THREAD

**Issue by JetForMe** [saghul/node-abstractsocket#2]
Your [test for \__linux\__] (https://github.com/saghul/node-abstractsocket/blob/master/src/abstract_socket.cc#L5) prevents this code from building on OS X. Perhaps test against \__POSIX\__ or similar?

**Comment by saghul** [comment]
OSX doesn't support abstract sockets, this works on Linux only.

**Comment by JetForMe** [comment]
Oh, I see. I took a look and thought it was just regular sockets use. Crap.

**Comment by martpie** [comment]
Question, I just want to *build* this library from macOS, but not *execute* it, is it possible?

macOS being UNIX-based, compiling this library should not be a problem, no?

My usecase is I have a dependency in my Electron app that is only executed/required on Linux, but my development machine is a MacBook. If I could avoid to build my app in one place and avoid having to run VMs just to build this library, it would be great :)

**Comment by saghul** [comment]
TBH I don't know how to do that at the npm level. Ideally this behaves like `fsevents`, which is macOS only and does nothing on Linux. If anyone knows how to to handle this, I'll be more than happy to take a PR.
