### ISSUE TITLE
New release for fix: use Nan::Set instead of v8::Object::Set

### ISSUE THREAD

**Issue by Robbos** [saghul/node-abstractsocket#21]
Hi,

I experienced a compile issue on abstract-socket which should be fixed with the following commit:
https://github.com/saghul/node-abstractsocket/commit/35b1b1491fabc04899bde5be3428abf5cf9cd528

I wondered why this fix has not made it into a release yet.

**Comment by saghul** [comment]
Oops. Published 2.1.1 now.
