### ISSUE TITLE
Use abstract-socket-rs without node-gyp

### ISSUE THREAD

**Issue by zhangyuang** [saghul/node-abstractsocket#23]
Refered `abstract-socket` i developed [abstract-socket-rs](https://github.com/zhangyuang/abstract-socket-rs) which implement the same api interface and is a pure js project.

# abstract-socket-rs

The ffi implemention of [abstract-socket](https://github.com/saghul/node-abstractsocket) based on [ffi-rs](https://github.com/zhangyuang/node-ffi-rs)

## Features

- No need to use node-gyp 😊
- Pure javascript project ✨
- Pre build all platform output 🤯

## Support platforms

- linux-x64-gnu
- linux-x64-musl
- linux-arm64-gnu
- linux-arm64-musl

## How to use

The api interface is the same as [abstract-socket](https://github.com/saghul/node-abstractsocket).

**Comment by saghul** [comment]
It's not pure JS, just because you provide prebuilds it doesn't magically make it not written in Rust. You also need to run `ldd`, and most importantly, people need to trust the binaries you checked in into your repo.

After the `xz` fiasco, I'd rather just build from source.
