### ISSUE TITLE
Is this needed for new versions of node?

### ISSUE THREAD

**Issue by georgir** [saghul/node-abstractsocket#8]
My tests show the core net library handling paths starting with '\0' just fine since 0.12, so is this module needed any more?
Perhaps a note in the README.md should clarify it is redundand unless you are on 0.10 or older...

**Comment by saghul** [comment]
@georgir Node does not yet support abstract Unix domain sockets. This module is still needed if you want to use those. The problem is not in Node per se, but in libuv.

**Comment by georgir** [comment]
Ah you are right. I tested only that net.createServer(...).listen('\0test') did not create ' test' file, and was connectable by net.connect('\0test').
It seems it does indeed create/connect to an abstract unix socket... but its name is still misinterpreted. It is listed as just "@" in lsof and net.connect('\0anything') connects to it.
Sorry for the noise.
